# Generated by Django 3.2.8 on 2021-10-10 22:26

from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        old_profile = apps.get_model('oc_lettings_site', 'Profile')
    except LookupError:
        # The old app isn't installed.
        return

    new_profile = apps.get_model('profiles', 'Profile')
    new_profile.objects.bulk_create(
        new_profile(user=old_object.user,
                    favorite_city=old_object.favorite_city
        )
        for old_object in old_profile.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ('profiles', '0001_initial'),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))
