# Generated by Django 3.2.8 on 2021-10-10 22:51


from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        old_address = apps.get_model('oc_lettings_site', 'Address')
        old_letting = apps.get_model('oc_lettings_site', 'Letting')
    except LookupError:
        # The old app isn't installed.
        return

    new_address = apps.get_model('lettings', 'Address')
    new_address.objects.bulk_create(
        new_address(number=old_object.number,
                    street=old_object.street,
                    city=old_object.city,
                    state=old_object.state,
                    zip_code=old_object.zip_code,
                    country_iso_code=old_object.country_iso_code
        )
        for old_object in old_address.objects.all()
    )

    new_letting = apps.get_model('lettings', 'Letting')
    new_letting.objects.bulk_create(
        new_letting(title=old_object.title,
                    address=new_address.objects.get(pk=old_object.address.pk)
        )
        for old_object in old_letting.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ('lettings', '0001_initial'),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))