version: 2.1

orbs:
  python: circleci/python@1.2

# Define a job to be invoked later in a workflow.
jobs:
  build-lint-test: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Lint
          # This assumes black, isort and flake8 are installed via the install-package step above
          command: |
            black . --check --config black.cfg
            isort . --check
            flake8 .
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-lint-test